// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDooK2rkQyJ8t_9ZnynsNTmpTVn-UIq4Yc',
    appId: '1:746756454279:web:8a90d07bc5958eda834522',
    messagingSenderId: '746756454279',
    projectId: 'owork-app',
    authDomain: 'owork-app.firebaseapp.com',
    storageBucket: 'owork-app.appspot.com',
    measurementId: 'G-ZM6JYX0V9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHmeE4YOLUj2og3vugyg-PlMOAnOiKFM8',
    appId: '1:746756454279:android:da8d776967413b2b834522',
    messagingSenderId: '746756454279',
    projectId: 'owork-app',
    storageBucket: 'owork-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2SFXrdNtgxXkIX0YNqaLXyUXxibDWLPo',
    appId: '1:746756454279:ios:058d98187678bfb6834522',
    messagingSenderId: '746756454279',
    projectId: 'owork-app',
    storageBucket: 'owork-app.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2SFXrdNtgxXkIX0YNqaLXyUXxibDWLPo',
    appId: '1:746756454279:ios:8873443ec207cfcf834522',
    messagingSenderId: '746756454279',
    projectId: 'owork-app',
    storageBucket: 'owork-app.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
